apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-app
  template:
    metadata:
      labels:
        app: solar-app
    spec:
      containers:
      - name: solar-app
        image: jqs/kubernetes:agular
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085

---

apiVersion: v1
kind: Service
metadata:
  name: solar-app
spec:
  type: NodePort
  selector:
    app: solar-app
  ports:
  - port: 80
    targetPort: 8085

